spring.datasource.url=jdbc:mysql://localhost:3306/ksrtc_bus_timetable
spring.datasource.username=root
spring.datasource.password=Akhilpoorvi0506

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
geoapify.api.url=https://api.geoapify.com/v1/routing
geoapify.api.key=${GEOAPIFY_API_KEY}